In [1]:
import numpy as np
import pandas as pd
import scipy as sp
import math

In [52]:
a=pd.read_csv(r'C:\Users\arkad\Downloads\Datasets\avocado.csv')
a

Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0               0  2015-12-27          1.33      64236.62  1036.74   54454.85   
1               1  2015-12-20          1.35      54876.98   674.28   44638.81   
2               2  2015-12-13          0.93     118220.22   794.70  109149.67   
3               3  2015-12-06          1.08      78992.15  1132.00   71976.41   
4               4  2015-11-29          1.28      51039.60   941.48   43838.39   
...           ...         ...           ...           ...      ...        ...   
18244           7  2018-02-04          1.63      17074.83  2046.96    1529.20   
18245           8  2018-01-28          1.71      13888.04  1191.70    3431.50   
18246           9  2018-01-21          1.87      13766.76  1191.92    2452.79   
18247          10  2018-01-14          1.93      16205.22  1527.63    2981.04   
18248          11  2018-01-07          1.62      17489.58  2894.77    2356.13   

         4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0       48.16     8696.87     8603.62       93.25          0.0  conventional   
1       58.33     9505.56     9408.07       97.49          0.0  conventional   
2      130.50     8145.35     8042.21      103.14          0.0  conventional   
3       72.58     5811.16     5677.40      133.76          0.0  conventional   
4       75.78     6183.95     5986.26      197.69          0.0  conventional   
...       ...         ...         ...         ...          ...           ...   
18244    0.00    13498.67    13066.82      431.85          0.0       organic   
18245    0.00     9264.84     8940.04      324.80          0.0       organic   
18246  727.94     9394.11     9351.80       42.31          0.0       organic   
18247  727.01    10969.54    10919.54       50.00          0.0       organic   
18248  224.53    12014.15    11988.14       26.01          0.0       organic   

       year            region  
0      2015            Albany  
1      2015            Albany  
2      2015            Albany  
3      2015            Albany  
4      2015            Albany  
...     ...               ...  
18244  2018  WestTexNewMexico  
18245  2018  WestTexNewMexico  
18246  2018  WestTexNewMexico  
18247  2018  WestTexNewMexico  
18248  2018  WestTexNewMexico  

[18249 rows x 14 columns]

In [65]:
def bhep_test_statistic(data, smoothing_parameter=1):
    n=data.shape[0]
    d=data.shape[1]
    if n <= d:
        print('not enough data!')
    S_n = np.cov(data, rowvar=False, bias=True)
    S_n_inverse_square_root = sp.linalg.sqrtm(np.linalg.inv(S_n))
    y_n=(data-np.mean(data, axis=0)) @ S_n_inverse_square_root
    jk_sum=0#считаем сумму по j,k из формулы тестовой статистики BHEP
    for j in range(n):
        for k in range(n):
            jk_sum+=np.exp(-(smoothing_parameter**2)*np.sum(np.square(data[j,:]-data[k,:]))/2)
    j_sum=0#считаем сумму по j из формулы тестовой статистики BHEP
    for j in range(n):
        j_sum+=np.exp(-(smoothing_parameter**2)*np.sum(np.square(data[j,:]))/(2*(1+smoothing_parameter**2)))
    bhep_test_statistic=(jk_sum/n) - (2*j_sum/((1+smoothing_parameter**2)**(d/2))) + n/((1+2*(smoothing_parameter**2))**(d/2))
    return bhep_test_statistic

In [67]:
def bhep_test(data, smoothing_parameter=1, sim_num=300):
    n=data.shape[0]
    d=data.shape[1]
    d_cov = np.cov(data, rowvar=False, bias=True)
    d_mean = data.mean(axis=0)
    if n <= d:
        print('not enough data!')
    a=[]
    for i in range(sim_num):
        print(f'progress={i}')
        a.append(bhep_test_statistic(rng.multivariate_normal(mean=d_mean, cov=d_cov, size=n), smoothing_parameter=smoothing_parameter))
    bh_stat=bhep_test_statistic(data=data, smoothing_parameter=smoothing_parameter)
    distr_func=0
    for i in a:
        if bh_stat>i:
            distr_func+=1
        if bh_stat==i:
            print('for some reason two statistics are the same')
    distr_func/=sim_num
    return distr_func, bh_stat, a

In [210]:
b=a[a['region']=='Albany'][['AveragePrice','Total Volume', '4046', '4225', '4770', 'Total Bags', 'Small Bags', 'Large Bags']]
b['Total Volume']=b['Total Volume']/100000
b['4046']=b['4046']/10000
b['4225']=b['4225']/100000
b['4770']=b['4770']/1000
b['Total Bags']=b['Total Bags']/10000
b['Small Bags']=b['Small Bags']/10000
b['Large Bags']=b['Large Bags']/10000
c=b[['Total Volume',  'Total Bags', 'Small Bags', 'Large Bags']]
data_sample=c.to_numpy()
(data_sample.min(axis=0),data_sample.max(axis=0))

(array([0.007742, 0.050344, 0.050344, 0.      ]),
 array([2.1673847, 3.680679 , 3.012631 , 2.720598 ]))

In [211]:
bhep_test_statistic(data_sample)

97.99810697753375

In [213]:
bhep_test(data_sample, sim_num=100)

progress=0
progress=1
progress=2
progress=3
progress=4
progress=5
progress=6
progress=7
progress=8
progress=9
progress=10
progress=11
progress=12
progress=13
progress=14
progress=15
progress=16
progress=17
progress=18
progress=19
progress=20
progress=21
progress=22
progress=23
progress=24
progress=25
progress=26
progress=27
progress=28
progress=29
progress=30
progress=31
progress=32
progress=33
progress=34
progress=35
progress=36
progress=37
progress=38
progress=39
progress=40
progress=41
progress=42
progress=43
progress=44
progress=45
progress=46
progress=47
progress=48
progress=49
progress=50
progress=51
progress=52
progress=53
progress=54
progress=55
progress=56
progress=57
progress=58
progress=59
progress=60
progress=61
progress=62
progress=63
progress=64
progress=65
progress=66
progress=67
progress=68
progress=69
progress=70
progress=71
progress=72
progress=73
progress=74
progress=75
progress=76
progress=77
progress=78
progress=79
progress=80
progress=81
progress=82
progress=83
pr

(0.83,
 97.99810697753375,
 [96.24234915909896,
  86.62665870361707,
  94.12984157285801,
  88.11246168851001,
  92.79309863092851,
  99.14383871472393,
  101.43212363233545,
  96.69215406607083,
  95.56808142665642,
  94.00503999367754,
  96.9550028009411,
  89.3026140773885,
  93.60641709928404,
  100.6174432260259,
  89.25618442558738,
  91.3598983722948,
  88.19335539648434,
  92.81400248250583,
  86.66768075556537,
  96.08264739285696,
  91.55121717524403,
  96.06548585917362,
  98.95086444336538,
  102.14855263069663,
  95.27901331316737,
  96.47055998295919,
  86.70302579983448,
  99.06425202958646,
  94.0541573184148,
  95.14333217829663,
  87.54536324564519,
  87.39974164764806,
  92.11779861364016,
  93.43945034361458,
  86.25116513131526,
  95.64167214860126,
  99.32773473202309,
  93.96586114471953,
  94.68317519808079,
  91.92594761478848,
  99.44303301243987,
  92.28110685602765,
  92.66788363677817,
  92.68918204030248,
  92.68681580408715,
  84.81272239345346,
  107.071

In [34]:
d=6 #размерность наблюдений
n=330 #число наблюдений
alpha=0.05 #уровень значимости 
generating_mean=np.zeros(d)
covar_generating_matrix=[[1,0.3966,0.3688,0.1764,-0.4632,0.2939],[0.3966,1,0.0232,-0.0854,0.0193,0.2191],[0.3688,0.0232,1,0.0494,-0.1350,-0.2376],[0.1764,-0.0854,0.0494,1,-0.4671,0.1135],[-0.4632,0.0193,-0.1350,-0.4671,1,-0.3656],[0.2939,0.2191,-0.2376,0.1135,-0.3656,1]]
np.linalg.det(np.array(covar_generating_matrix))
data_sample=np.random.multivariate_normal(generating_mean,covar_generating_matrix, size=n)
data_sample.shape

(330, 6)

In [35]:
bhep_test_statistic(data_sample)

2.338714330512504

In [178]:
rng

Generator(PCG64) at 0x1E613909D60

In [204]:
0.95**100

0.0059205292203339975

In [215]:
data_sample

array([[6.4236620e-01, 8.6968700e-01, 8.6036200e-01, 9.3250000e-03],
       [5.4876980e-01, 9.5055600e-01, 9.4080700e-01, 9.7490000e-03],
       [1.1822022e+00, 8.1453500e-01, 8.0422100e-01, 1.0314000e-02],
       ...,
       [3.3465400e-02, 3.0788600e-01, 3.0788600e-01, 0.0000000e+00],
       [4.1409500e-02, 3.8317800e-01, 3.8317800e-01, 0.0000000e+00],
       [4.8169000e-02, 4.3612200e-01, 4.3578900e-01, 3.3300000e-04]])